---
kind: Service
apiVersion: v1
metadata:
  name: spring-boot-hello
  namespace: springboot
spec:
  # type: LoadBalancer
  type: ClusterIP
  selector:
    app: spring-boot-hello
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
